"""add year field

Revision ID: 3918e9651030
Revises: a2afe42b4c71
Create Date: 2025-11-23 12:20:46.169508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3918e9651030'
down_revision: Union[str, None] = 'a2afe42b4c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'forum_likes', 'forum_posts', ['post_id'], ['id'])
    op.add_column('questions', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_questions_year'), 'questions', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_year'), table_name='questions')
    op.drop_column('questions', 'year')
    op.drop_constraint(None, 'forum_likes', type_='foreignkey')
    # ### end Alembic commands ###
