"""Add practice test support to attempts

Revision ID: 5ed38597ef47
Revises: 80250f060de0
Create Date: 2025-11-30 14:05:47.241791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed38597ef47'
down_revision: Union[str, None] = '80250f060de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('attempts', sa.Column('exam_type_id', sa.Integer(), nullable=True))
    op.add_column('attempts', sa.Column('is_practice', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'attempts', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'attempts', 'exam_types', ['exam_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_column('attempts', 'is_practice')
    op.drop_column('attempts', 'exam_type_id')
    op.drop_column('attempts', 'subject_id')
    # ### end Alembic commands ###
