"""Add time_taken column to attempts table

Revision ID: 80250f060de0
Revises: fb29de819390
Create Date: 2025-11-30 13:33:51.704667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80250f060de0'
down_revision: Union[str, None] = 'fb29de819390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('time_taken', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'time_taken')
    # ### end Alembic commands ###
