"""Add question_image field to questions table

Revision ID: 89487c4827b8
Revises: edd93bda6b69
Create Date: 2025-11-09 15:09:14.851277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89487c4827b8'
down_revision: Union[str, None] = 'edd93bda6b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.add_column('questions', sa.Column('question_image', sa.String(), nullable=True))
    op.create_foreign_key(None, 'test_questions', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_questions', type_='foreignkey')
    op.drop_column('questions', 'question_image')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    # ### end Alembic commands ###
